/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetvin2;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dadou
 */
public class frmVin extends javax.swing.JFrame {

    ArrayList<Bouteille> mesBouteilles;
    
    
    
    /**
     * Creates new form frmVin
     */
    public frmVin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMillesime = new javax.swing.JLabel();
        fieldMillesime = new javax.swing.JTextField();
        txtPrix = new javax.swing.JLabel();
        fieldPrix = new javax.swing.JTextField();
        txtCepage = new javax.swing.JLabel();
        txtCouleur = new javax.swing.JLabel();
        fieldCepage = new javax.swing.JTextField();
        fieldCouleur = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVin = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        caveValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pourcentageRouge = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pourcentageBlanc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Projet Vin");

        jLabel2.setText("Liste des bouteilles");

        txtMillesime.setText("Millesime");

        fieldMillesime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMillesimeActionPerformed(evt);
            }
        });

        txtPrix.setText("Prix");

        fieldPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPrixActionPerformed(evt);
            }
        });

        txtCepage.setText("Cepage");

        txtCouleur.setText("Couleur");

        fieldCepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCepageActionPerformed(evt);
            }
        });

        fieldCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCouleurActionPerformed(evt);
            }
        });

        tblVin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Vin", "Quantite"
            }
        ));
        tblVin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVinMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVin);

        jLabel3.setText("Valeur de la cave");

        caveValue.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        caveValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        caveValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Pourcentage Rouge");

        pourcentageRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pourcentageRougeActionPerformed(evt);
            }
        });

        pourcentageBlanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pourcentageBlancActionPerformed(evt);
            }
        });

        jLabel5.setText("Pourcentage Blanc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtMillesime, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldMillesime, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(fieldCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(fieldCepage, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel4))
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(pourcentageRouge, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(pourcentageBlanc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(caveValue, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMillesime, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldMillesime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrix)
                            .addComponent(fieldPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCepage)
                            .addComponent(fieldCepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCouleur)
                            .addComponent(fieldCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(caveValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pourcentageRouge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pourcentageBlanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void fieldMillesimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMillesimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMillesimeActionPerformed

    private void fieldCepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCepageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCepageActionPerformed

    private void fieldPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPrixActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         DefaultTableModel dtmVin = new DefaultTableModel();
        dtmVin = (DefaultTableModel) tblVin.getModel();
        Vector v;
        
        Couleur blanc = new Couleur("Blanc");
        Couleur rouge = new Couleur("Rouge");
        
        
        Cepage beaujolais = new Cepage("Beaujolais");
        Cepage Sauvignon = new Cepage("Sauvignon");
        
        Vin vin1 = new Vin("Julienas", 2009, Sauvignon, blanc,19);
        Vin vin2 = new Vin("Morgon", 2011, beaujolais, rouge,8);
        Vin vin3 = new Vin("Champagne", 2005, Sauvignon, blanc,15);
        
        Bouteille b1 = new Bouteille(1, 5, vin1);
        Bouteille b2 = new Bouteille(2, 5, vin2);
        Bouteille b3 = new Bouteille(3, 10, vin3);
        
        mesBouteilles = new ArrayList<>();
        
        mesBouteilles.add(b3);
        mesBouteilles.add(b2);
        mesBouteilles.add(b1);
        
        double caveValueD=0;
        int nbrRouge = 0;
        int nbrBouteilleTotale=0;
        int nbrBlanc=0;

        for(Bouteille bout : mesBouteilles)
        {
            v=new Vector();
            v.add(bout.getIdBouteille());
            v.add(bout.getLeVin().getNomVin());
            v.add(bout.getQuantiteBouteille());
            dtmVin.addRow(v);
            caveValueD += bout.getQuantiteBouteille()*bout.getLeVin().getPrixduVin();
            
            nbrBouteilleTotale = nbrBouteilleTotale+ bout.getQuantiteBouteille();
            
            if(bout.getLeVin().getLaCouleur().getUneCouleur()== "Rouge"){
                nbrRouge = nbrRouge+bout.getQuantiteBouteille();
            }
            if(bout.getLeVin().getLaCouleur().getUneCouleur() == "Blanc"){
                nbrBlanc = nbrBlanc+bout.getQuantiteBouteille();
            }
            
            
        }
        double pourcentRouge = ((double)nbrRouge/(double)nbrBouteilleTotale)*100;
        System.out.println(pourcentRouge);
        caveValue.setText(String.valueOf(caveValueD));
        pourcentageRouge.setText(String.valueOf(pourcentRouge)+"%");
        
         double pourcentBlanc = ((double)nbrBlanc/(double)nbrBouteilleTotale)*100;
        System.out.println(pourcentBlanc);
        caveValue.setText(String.valueOf(caveValueD));
        pourcentageBlanc.setText(String.valueOf(pourcentBlanc)+"%");
        
        
        
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void pourcentageRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pourcentageRougeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pourcentageRougeActionPerformed

    private void tblVinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVinMouseClicked
        // TODO add your handling code here:
      this.fieldMillesime.setText("");
      this.fieldPrix.setText("");
      this.fieldCepage.setText("");
      this.fieldCouleur.setText("");
      
      int numBouteille = Integer.parseInt(this.tblVin.getValueAt(this.tblVin.getSelectedRow(),0).toString());
      
      int monMillesime=0;
      double monPrix=0;
      String monCepage="";
      String maCouleur="";
      
      
      for(Bouteille bout: mesBouteilles)
      {
          if(bout.getIdBouteille()==numBouteille)
          {
              monMillesime=bout.getLeVin().getMillesimeVin();
              monPrix=bout.getLeVin().getPrixduVin();
              monCepage=bout.getLeVin().getNomVin();
              maCouleur=bout.getLeVin().getLaCouleur().getUneCouleur();
                      
                     
          }
      }
      
        this.fieldMillesime.setText(String.valueOf(monMillesime));
        this.fieldPrix.setText(String.valueOf(monPrix));
        this.fieldCepage.setText(String.valueOf(monCepage));
        this.fieldCouleur.setText(String.valueOf(maCouleur));
        
        
        
        
        
    }//GEN-LAST:event_tblVinMouseClicked

    private void pourcentageBlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pourcentageBlancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pourcentageBlancActionPerformed

    private void fieldCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCouleurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCouleurActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caveValue;
    private javax.swing.JTextField fieldCepage;
    private javax.swing.JTextField fieldCouleur;
    private javax.swing.JTextField fieldMillesime;
    private javax.swing.JTextField fieldPrix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pourcentageBlanc;
    private javax.swing.JTextField pourcentageRouge;
    private javax.swing.JTable tblVin;
    private javax.swing.JLabel txtCepage;
    private javax.swing.JLabel txtCouleur;
    private javax.swing.JLabel txtMillesime;
    private javax.swing.JLabel txtPrix;
    // End of variables declaration//GEN-END:variables
}
